### ISSUE TITLE
Moving down menu highlights options

### ISSUE THREAD

**Issue by ludwj61** [RishabhRD/nvim-lsputils#14] opened 2020-10-29 15:57 UTC
Hello, with the last couple updates to this plugin, I noticed that when navigating the code action menu, options that I scroll over stay highlighted instead of just the current action. 

For example, this is what it looks like when I trigger a code action and press ``j`` three times:
![image](https://user-images.githubusercontent.com/42984254/97598547-79fca780-19dd-11eb-8f7a-b30fc5857478.png)

I am on the latest nvim nightly, arch, and using the latest version of this plugin.

Thanks for your work!

**Comment by RishabhRD** [comment] 2020-10-29 16:04
Are you experiencing the same with references, symbols, etc?

**Comment by ludwj61** [comment] 2020-10-29 16:46
No actually, it's just the popups from code action

**Comment by RishabhRD** [comment] 2020-10-29 18:43
I was not able to replicate the behavior. However, I removed some suspicious code from popfix. Can you try 'issue14' branch of popfix? I just pushed it recently just for check. It may or may not work because I was not able to reproduce the bug.

**Comment by ludwj61** [comment] 2020-10-29 19:21
Yep, using the issue14 branch fixes the issue, thanks for the quick fix!

**Comment by RishabhRD** [comment] 2020-10-29 19:23
OK! I would merge that in master just after completing few checks. :smiley:

**Comment by RishabhRD** [comment] 2020-10-29 19:51
popfix issue14 branch merged to master! closing the issue then. Thanks for reporting :smile:

**Closed by RishabhRD** 2020-10-29 19:51 UTC
